import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
    title: "Terms & Conditions",
    description: "Terms of service for using SiteER scans, reports, and implementation services.",
    alternates: { canonical: "/terms" },
};

const sections = [
    {
        title: "1. Agreement to Terms",
        body: `By accessing or using SiteER ("the Service"), you agree to be bound by these Terms & Conditions. If you do not agree, do not use the Service. These terms apply to all visitors, users, and purchasers of SiteER products and services.`,
    },
    {
        title: "2. Services Description",
        body: `SiteER provides automated website diagnostic scans, graded reports, revenue-leak estimates, and optional implementation services. The Free ER Scan and paid reports are informational products. The ER Fix Pack ($497) is a professional service in which our team implements technical improvements to your website.`,
    },
    {
        title: "3. Scan Results & Estimates",
        body: `All scan grades, issue lists, and revenue-leak estimates are directional and informational in nature. They are generated by automated analysis and do not constitute financial, legal, or professional advice. Estimates of monthly revenue loss are projections based on industry benchmarks and user-provided inputs — they are not guarantees of actual performance or earnings.`,
    },
    {
        title: "4. Payment & Pricing",
        body: `The ER Fix Pack is billed at a flat rate of $497 USD. The Deep ER Report is billed at $49 USD. Payment is due at the time of purchase. All prices are in US dollars. We reserve the right to change pricing at any time; changes do not affect existing paid orders.`,
    },
    {
        title: "5. Money-Back Guarantee",
        body: `The ER Fix Pack carries a grade-improvement guarantee: if we do not raise your SiteER score by at least 20 points compared to your pre-fix baseline scan, you receive a full refund. The guarantee applies only to work completed within the defined ER Fix Pack scope and does not apply to factors outside our control (e.g., third-party platform limitations, CMS restrictions, server configuration). Refund requests must be made within 14 days of delivery.`,
    },
    {
        title: "6. User Responsibilities",
        body: `You are responsible for the URLs, business data, and any other information you submit through SiteER. You represent that you have authority to scan and authorize changes to any website you submit. You agree not to use SiteER to scan websites you do not own or have permission to audit.`,
    },
    {
        title: "7. Intellectual Property",
        body: `All SiteER software, report formats, grading methodology, and brand assets are the property of COAIBAKERSFIELD.COM and its licensors. Your scan reports are provided for your personal or business use only. You may not resell, redistribute, or white-label SiteER reports or tooling without written permission.`,
    },
    {
        title: "8. Limitation of Liability",
        body: `To the maximum extent permitted by law, SiteER and COAIBAKERSFIELD.COM are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim is limited to the amount you paid for the specific service giving rise to the claim.`,
    },
    {
        title: "9. Privacy",
        body: `Your use of SiteER is also governed by our Privacy Policy, available at siteer.dev/privacy. By using the Service, you consent to the data practices described therein.`,
    },
    {
        title: "10. Changes to Terms",
        body: `We may update these terms at any time. Continued use of the Service after changes are posted constitutes acceptance of the updated terms. We will make reasonable efforts to notify users of material changes.`,
    },
    {
        title: "11. Governing Law",
        body: `These Terms are governed by the laws of the State of California, United States. Any disputes shall be resolved in Kern County, California.`,
    },
    {
        title: "12. Contact",
        body: `Questions about these terms? Contact us at jasonm@coaibakersfield.com or call (661) 569-4244. Mailing address: COAIBAKERSFIELD.COM, Bakersfield, CA 93301.`,
    },
];

export default function TermsPage() {
    return (
        <>
            <SiteHeader />
            <main className="er-container" style={{ padding: "64px 0 0", maxWidth: 800 }}>
                <p style={{ color: "var(--er-red)", textTransform: "uppercase", letterSpacing: ".13em", fontSize: "0.78rem", fontWeight: 950, marginBottom: 12 }}>Legal</p>
                <h1 style={{ fontSize: "clamp(2rem, 4vw, 3.2rem)", letterSpacing: "-.04em", marginBottom: 8 }}>Terms & Conditions</h1>
                <p style={{ color: "var(--er-muted)", fontSize: "0.9rem", marginBottom: 48 }}>Last updated: May 1, 2026 · Effective immediately</p>

                <div style={{ display: "grid", gap: 36 }}>
                    {sections.map((s) => (
                        <section key={s.title}>
                            <h2 style={{ fontSize: "1.1rem", fontWeight: 800, marginBottom: 12, color: "white" }}>{s.title}</h2>
                            <p style={{ color: "var(--er-muted)", lineHeight: 1.8, fontSize: "0.96rem" }}>{s.body}</p>
                        </section>
                    ))}
                </div>

                <div style={{ marginTop: 64, borderRadius: 20, padding: 24, background: "rgba(255,255,255,.04)", border: "1px solid rgba(255,255,255,.1)" }}>
                    <p style={{ color: "var(--er-muted)", fontSize: "0.9rem", lineHeight: 1.7 }}>
                        <strong style={{ color: "white" }}>Questions?</strong> Email <a href="mailto:jasonm@coaibakersfield.com" style={{ color: "var(--er-cyan)" }}>jasonm@coaibakersfield.com</a> or call <a href="tel:+16615694244" style={{ color: "var(--er-cyan)" }}>(661) 569-4244</a>.
                    </p>
                </div>
            </main>
            <SiteFooter />
        </>
    );
}
